const ROOT_ROUTE = `/webpages`;

const PERMISSION_KEYS = {
  CREATE_WEBPAGE_PERMISSION: 'CREATE_WEBPAGE_PERMISSION',
  DELETE_WEBPAGE_PERMISSION: 'DELETE_WEBPAGE_PERMISSION',
  VIEW_WEBPAGE_PERMISSION: 'VIEW_WEBPAGE_PERMISSION',
  UPDATE_WEBPAGE_PERMISSION: 'UPDATE_WEBPAGE_PERMISSION',
  ACTIVE_WEBPAGE_PERMISSION: 'ACTIVE_WEBPAGE_PERMISSION',
};

export { ROOT_ROUTE, PERMISSION_KEYS };
