const ROOT_ROUTE = `/permissions`;

const PERMISSION_KEYS = {
  CREATE_PERMISSION: 'CREATE_PERMISSION',
  DELETE_PERMISSION: 'DELETE_PERMISSION',
  VIEW_PERMISSION: 'VIEW_PERMISSION',
  UPDATE_PERMISSION: 'UPDATE_PERMISSION',
  ACTIVE_PERMISSION: 'ACTIVE_PERMISSION',
};

export { ROOT_ROUTE, PERMISSION_KEYS };
