const ROOT_ROUTE = `/roles`;

const ROLE_ACTION_TABLE_PERMISSION_KEYS = {
  CREATE_ROLE_PERMISSION: 'CREATE_ROLE_PERMISSION',
  DELETE_ROLE_PERMISSION: 'DELETE_ROLE_PERMISSION',
  VIEW_ROLE_PERMISSION: 'VIEW_ROLE_PERMISSION',
  UPDATE_ROLE_PERMISSION: 'UPDATE_ROLE_PERMISSION',
  ACTIVE_ROLE_PERMISSION: 'ACTIVE_ROLE_PERMISSION',
};

export { ROOT_ROUTE, ROLE_ACTION_TABLE_PERMISSION_KEYS };
