const ROOT_ROUTE = `/users`;

const PERMISSION_KEYS = {
  CREATE_USER_PERMISSION: 'CREATE_USER_PERMISSION',
  DELETE_USER_PERMISSION: 'DELETE_USER_PERMISSION',
  VIEW_USER_PERMISSION: 'VIEW_USER_PERMISSION',
  UPDATE_USER_PERMISSION: 'UPDATE_USER_PERMISSION',
  ACTIVE_USER_PERMISSION: 'ACTIVE_USER_PERMISSION',
};

export { ROOT_ROUTE, PERMISSION_KEYS };
